### ISSUE TITLE
[Bug] Big problem with "rotating_shop" system.

### ISSUE THREAD

**Issue by NoltoxGit** [nulli0n/ExcellentShop-spigot#36]
Hello,
I just noticed a problem with **rotating_shop**.
I have set the parameter to `FIXED` mode, and that it only updates on Sundays at 18:000:00.

And the rotating shop has just reset today at 18:00:00, even though it's not Sunday.

Here is my config:
```yml
Name: <white>%img_offset_-46%%img_gui_boost_base%
Description:
- <gray>Shop with items changing</gray>
- <gray>every 24 hours.</gray>
Permission_Required: false
Layout:
  Name: default
Citizens:
  Attached_NPC: ''
Transaction_Allowed:
  SELL: true
  BUY: false
Rotation:
  Type: FIXED
  Products:
    Min_Amount: 3
    Max_Amount: 3
    Slots: 11,13,15
  Fixed:
    SUNDAY:
    - '18:00:00'
    WEDNESDAY: []
    TUESDAY: []
    THURSDAY: []
    SATURDAY: []
    MONDAY: []
    FRIDAY: []
Icon:
  Material: ENDER_EYE
```

## Here's my solution:
The way that *(would suit me best)* would be to be able to disable automatic store change, and only be able to change it with a command like `/vshop rotate SHOP_NAME`.
